### ISSUE TITLE
general layout

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider.github.io#57] opened 2016-03-22 21:57 UTC
The layout as a whole looks a little awkward: it may be better to align the sections the same way as the images, and also not just vertically?

**Comment by crucialfelix** [comment] 2016-03-22 22:06
I would just put a whole new theme / framework in. update it to 2016 style

**Comment by telephon** [comment] 2016-03-23 18:36
if you could do that without too much effort, that would be great.

**Comment by telephon** [comment] 2016-11-13 14:27
it would be even great if you can do it with to much effort!

**Comment by telephon** [comment] 2016-11-13 14:28
(hm, maybe not so...)

**Comment by snappizz** [comment] 2016-11-13 17:44
This has gone undone for a long time because revamping the website is a massively laborious and thankless task. I would volunteer to redesign it but I don't have the bandwidth right now.

**Comment by telephon** [comment] 2016-11-13 19:47
I had assumed it would already look a lot better if it just used a different css. It could actually be rather plain, it already seems a bit too much (incongruent) formatting involved …

Maybe an intermediate simple step?

**Comment by crucialfelix** [comment] 2016-11-13 20:10
I have a lot more experience doing these now. I'll see if I can put a new more minimal look on it.

**Comment by telephon** [comment] 2018-02-28 12:50
I continue the discussion here, because it is still the same topic. It would be good to thoroughly revise the stylesheet for the whole thing. Now that we are using markdown for the pages again, the range of things to be specified is smaller anyway.

**Comment by telephon** [comment] 2018-02-28 12:51
What about first replacing it first by the standard github stylesheet and then tweaking that?

**Comment by snappizz** [comment] 2018-07-25 20:44
i think we can subsume this old issue into #175.

**Comment by gusano** [comment] 2022-03-19 02:39
Closing as duplicate of #175

**Closed by gusano** 2022-03-19 02:39 UTC
